services:
  app:
    build: ./app
    env_file: 'backend.env'
    depends_on:
      - llm
    volumes:
      - ./reports:/app/reports
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      
  llm:
    provider:
      type: model
      options:
        model: ${LLM_MODEL_NAME:-ai/qwen3:8B-Q4_K_M}
